### ISSUE TITLE
AttnFuncWithCP with seq_len==1 breaks

### ISSUE THREAD

**Issue by MaciejBalaNV** [NVIDIA/TransformerEngine#1070]
TE Attention breaks here if sequence length is equal to 1, e.g. [here](https://github.com/NVIDIA/TransformerEngine/blob/main/transformer_engine/pytorch/attention.py#L1661). It was not the case until this [commit](https://github.com/NVIDIA/TransformerEngine/commit/9709147e35ec09062d29712042c3aba3cb1ab57e). If seqlen==1 case is not supported, it would be nice to add a check and meaningful error message.

**Comment by ptrendx** [comment]
@xrennvidia and @cyanguwa Could you take a look?

**Comment by xrennvidia** [comment]
Hi @MaciejBalaNV 

Thanks for reaching out. Could you please clarify what seqlen=1 means? Does it mean your total sequence length is 1? or sequence chunk length in each GPU is 1?

With CP, you need to guarantee your total sequence length is divisible by CP*2, so that each GPU will get at least 2 tokens.

**Comment by xrennvidia** [comment]
Hi @MaciejBalaNV 

[Is this what you are looking for?](https://github.com/NVIDIA/TransformerEngine/pull/1060/commits/61d615a34c35629afe29404cc866b4bb6cc661cb)

**Comment by MaciejBalaNV** [comment]
Hey @xrennvidia , yes, this assert looks correct for the bug I've observed. Thanks, I believe we can close this issue.
