### ISSUE TITLE
Unable to import transformer_engine.pytorch using TE v1.9.0

### ISSUE THREAD

**Issue by snarayan21** [NVIDIA/TransformerEngine#1147]
Hey, when installing transformer engine as `pip install transformer-engine==1.9.0` I'm unable to simply `import transformer_engine.pytorch` -- it causes this error:

```
>>> import transformer_engine.pytorch
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/transformer_engine/pytorch/__init__.py", line 22, in _load_library
    so_path = next(so_dir.glob(f"*.{extension}"))
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
StopIteration

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3/dist-packages/transformer_engine/pytorch/__init__.py", line 34, in <module>
    _load_library()
  File "/usr/lib/python3/dist-packages/transformer_engine/pytorch/__init__.py", line 25, in _load_library
    so_path = next(so_dir.glob(f"*.{extension}"))
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
StopIteration
```

I tried modifying the library load code but to no avail. This also happens with the newer post1 version as well. Is there something that's broken for installing from pypi? I'm able to install using the command below:
```
NVTE_FRAMEWORK=pytorch CMAKE_BUILD_PARALLEL_LEVEL=4 MAX_JOBS=4 pip install git+https://github.com/NVIDIA/TransformerEngine.git@fc98961
```
This installs TE from [this commit](https://github.com/NVIDIA/TransformerEngine/pull/884), which was immediately prior to the build system refactor commit [here](https://github.com/NVIDIA/TransformerEngine/pull/877).

Would be great to resolve this so we can directly start adding TE as a pip dependency instead of having to install it via docker images. Thanks!

**Comment by snarayan21** [comment]
Resolved by doing `pip install transformer-engine[pytorch]`!

Thank you @ksivaman for the help!

**Comment by srelus** [comment]
I ran into the same issue where importing transformer_engine.pytorch fails immediately after a standard installation of the transformer-engine package from PyPI.

If you install it like this:

pip install transformer-engine

and then try to import it:

import transformer_engine.pytorch

you get a StopIteration error. The reason is simple, but totally undocumented: the shared library (.so) that the module tries to load is missing, because the PyTorch backend is not installed by default.

This shared object (transformer_engine_torch.cpython-*.so) is required, but it's not part of the core package unless you explicitly install with the PyTorch extra.

This issue affects at least the following versions:

    transformer-engine==1.9.0
    transformer-engine==1.9.0.post1
    transformer-engine==2.1.0

And likely all other versions if installed without the extra.

The fix is very simple, but completely unintuitive. You need to install the package with the [pytorch] extra:

pip install 'transformer-engine[pytorch]' --extra-index-url https://pypi.ngc.nvidia.com/

This installs the core package, the compiled CUDA backend (transformer_engine_cu12), and the required .so file for PyTorch integration.

Once that’s done, importing transformer_engine.pytorch works without issues.

Why this is problematic:

    The error message (StopIteration) is misleading and gives no useful context.
    The default installation does not include essential components.
    The documentation and README don’t make it clear that [pytorch] is required.
    Most users will assume that pip install transformer-engine is enough, and they’ll get stuck.

What should be done:

The installation instructions should clearly tell PyTorch users to run:

pip install 'transformer-engine[pytorch]' --extra-index-url https://pypi.ngc.nvidia.com/

Otherwise, people will continue running into this exact problem and waste a lot of time figuring it out.
