### ISSUE TITLE
Cannot import transformer_engine_extensions

### ISSUE THREAD

**Issue by mindest** [NVIDIA/TransformerEngine#115]
### Issue
Hit error when simply `import transformer_engine_extensions`:
```text
ImportError: /usr/local/lib/python3.8/dist-packages/transformer_engine_extensions.cpython-38-x86_64-linux-gnu.so: undefined symbol: nvte_layernorm_bwd
```
Seems some necessary sources are not included: 
https://github.com/NVIDIA/TransformerEngine/blob/5a881a0834384460c2558cfbc40bc9ff0a6aa146/setup.py#L85-L89

Could this be solved? Thanks.
### Environment
- Host: DGX H100 (cuda_12.0.r12.0/compiler.32267302_0)
- Docker: `nvcr.io/nvidia/pytorch:23.02-py3`

### To reproduce
- `transformer_engine` is already installed in the above docker (v0.5.0), just run the `import` command in Python.
- Also tried installing the latest version from source via `NVTE_FRAMEWORK=pytorch pip install .`, but still met this error.

**Comment by timmoon10** [comment]
The easiest fix:
```python
import transformer_engine
import transformer_engine_extensions
```
This is because `transformer_engine_extensions`/`transformer_engine_jax` are pybind modules and some extra logic is required to figure out the install paths. See https://github.com/NVIDIA/TransformerEngine/blob/main/transformer_engine/common/__init__.py. For now these extension modules should be considered as internal implementation, although I'd be interested to hear if your use-case would benefit from making this more robust.

Pinging @trevor-m and @kaixih.

**Comment by mindest** [comment]
> ```python
> import transformer_engine
> import transformer_engine_extensions
> ```
It works. Thanks, @timmoon10
