### ISSUE TITLE
layer normalization after Linear

### ISSUE THREAD

**Issue by ftgreat** [NVIDIA/TransformerEngine#1150]
Is there any module for layer normalization after linear transformation? Thanks.

**Comment by timmoon10** [comment]
We don't have any particular kernel fusions for that pattern, so there's no harm in putting a LayerNorm module after the linear:
```python
linear = te.Linear(...)
norm = te.LayerNorm(...)
y = norm(linear(x))
```
Using the operation-based API (see https://github.com/NVIDIA/TransformerEngine/pull/1033), this could be:
```
layer = te.ops.Sequential(
    te.ops.Linear(...),
    te.ops.LayerNorm(...),
)
```
If we do find some kernel fusions for this pattern, we would probably implement it using the operation-based API instead of implementing a new module.

**Comment by ftgreat** [comment]
Hello, @timmoon10 

I am working on a two-layer MLP setup within a tensor parallelism context (e.g., tp=2), which consists of a TEColumnParallelLinear followed by a TERowParallelLinear. I’m looking to perform a LayerNorm operation right after the output from TEColumnParallelLinear, and importantly, I want each tensor parallel split (tp slice) to have its own independent LayerNorm.

Could you provide any suggestions on whether there is an existing module that supports this, or how one might go about adding this functionality? Thank you for your assistance!
