### ISSUE TITLE
question about Model FLOPs Utilization

### ISSUE THREAD

**Issue by jinz2014** [NVIDIA/TransformerEngine#1151]
In the article https://www.databricks.com/blog/turbocharged-training-optimizing-databricks-mosaic-ai-stack-fp8
Figure 2. Model FLOPs Utilization (MFU) across different model sizes and precisions. MFU represents the ratio of achieved TFLOPS to the peak TFLOPS possible on a GPU. It measures the efficiency of model training. Notably, the MFU with FP8 is lower than with BF16. This is because the theoretical computation capacity of FP8 is double that of BF16 on H100 GPUs. While FP8 performs more operations per second, its utilization is lower.

Could you please explain how the peak FP8 TFLOPS is computed ?  Thanks.

**Comment by timmoon10** [comment]
I believe the peak FP8 throughput is estimated based on the compute throughput of the FP8 tensor cores (caveat: I'm not involved with computing specs, so don't take this as an official statement). If we had perfect software and infinitely large data, the runtime of matrix multiplication would be completely determined by how quickly the GPU performs arithmetic operations. However, in real-life applications we experience some inefficiencies (e.g. kernel launch latencies, cache misses, pipeline bubbles) that prevent us from fully saturating the compute. FP8 training also requires extra logic for scaling factors, so that adds some more overhead compared to FP16/BF16 training.

**Comment by jinz2014** [comment]
The peak is 3,958 teraFLOPS and 3,341 teraFLOPS for H100 GPUs.  Is MFU equal to 703 (MPT-70b) divided by the peak ?

**Comment by timmoon10** [comment]
TE doesn't take advantage of sparsity, so peak FP8 perf on H100 is 1979 TFLOPS. Databricks achieved 703 TFLOPS with MPT-70b, so the result is 35.5% of peak performance.

**Comment by jinz2014** [comment]
I didn't know sparsity. Thanks.
