### ISSUE TITLE
installation guide for NVHPC SDK

### ISSUE THREAD

**Issue by jinz2014** [NVIDIA/TransformerEngine#1156]
Could you please provide an install guide for NVHPC SDK users ?  Thanks.

fatal error: cublas_v2.h: No such file or directory
fatal error: cusparse.h: No such file or directory

**Comment by timmoon10** [comment]
Could you provide more of the build log? These errors suggest that the compiler can't find some CUDA headers, so that makes me think that CUDA was not properly installed or CMake is not finding the right paths. As a first step, it may be helpful to add `nvcc` to your `PATH` and to set the `CUDA_PATH` environment variable.

Further guidance also depends on your use-case. If you are trying to use TE to accelerate a PyTorch workflow, you should first try getting PyTorch working by itself on your system. If you're trying to use TE's C API, I've been able to build TE in the `nvcr.io/nvidia/cuda:12.0.0-devel-ubuntu22.04` container with:
```bash
apt-get update
apt-get install -y git python3.9 pip ninja-build cudnn9-cuda-12
pip install cmake==3.21.0
pip install . -v
```
See [the unit test for a minimal TE build](https://github.com/NVIDIA/TransformerEngine/blob/fb749619ed768d732ccfecdd47249b8b8cbe6ba3/.github/workflows/build.yml#L10-L33).
