### ISSUE TITLE
when will there be a solution for loss optimization caused by Dgrad in TE?

### ISSUE THREAD

**Issue by duomicoding** [NVIDIA/TransformerEngine#1278]
Hi, professor， when will there be a solution for loss optimization caused by Dgrad in TE?  such as current scale strategy for Dgrad. Which version of TE may have the feature?

**Comment by timmoon10** [comment]
Can you explain what you mean by "loss optimization caused by Dgrad"?

If I understand correctly, you are referring to the fact that FP8 tends to hurt convergence? TE already supports per-tensor scaling to reduce the numerical error from FP8 training (see [the TE docs](https://docs.nvidia.com/deeplearning/transformer-engine/user-guide/examples/fp8_primer.html)). We have also been looking into other schemes like block scaling (see [our GTC 2024 talk](https://www.nvidia.com/en-us/on-demand/session/gtc24-s62457/)). That said, training degradation from quantization error will probably never be fully solved and users will still need to be thoughtful about whether the performance gains from low-precision data types are worth the training degradation from quantization error.

**Comment by duomicoding** [comment]
Thank you for your meaningful reply！by the way, how can I use per-tensor scaling in TE?  and a problem has been encountered: firstly, I have fp8 training for a while,  I avoid loss worse little by little， so I resume from fp8 checkpoint for bf16 continuous training. after a while, I switch to fp8 train for speed up, when resume from a bf16 checkpoint, I found the first loss of fp8 training is very different from the previous loss of  bf16 checkpoint resumed.  What might be the cause of this problem？and are there any good solutions for it?

**Comment by duomicoding** [comment]
@timmoon10 Thank you for your meaningful reply！by the way, how can I use per-tensor scaling in TE? and a problem has been encountered: firstly, I have fp8 training for a while, I avoid loss worse little by little， so I resume from fp8 checkpoint for bf16 continuous training. after a while, I switch to fp8 train for speed up, when resume from a bf16 checkpoint, I found the first loss of fp8 training is very different from the previous loss of bf16 checkpoint resumed. What might be the cause of this problem？and are there any good solutions for it?

**Comment by timmoon10** [comment]
TE automatically does per-tensor scaling:
```python
layer = transformer_engine.pytorch.Linear(...)
with transformer_engine.pytorch.fp8_autocast():  # Forward scales are updated when exiting context
    y = layer(x)
y.sum().backward()  # Backward scales are updated when autograd finishes
```

If you're only seeing a bad loss value in the first step after loading a checkpoint, it's probably a problem with the initial FP8 scales. The delayed scaling recipe used in TE (see [TE docs](https://docs.nvidia.com/deeplearning/transformer-engine/user-guide/examples/fp8_primer.html)) keeps a history of previously seen values and uses them to estimate good FP8 scales (maximize dynamic range while avoiding overflows). However, there is no history in the first step after loading a BF16 model, so we just set the FP8 scales to 1.0. The solution is to do a calibration step in BF16:
```python
layer = transformer_engine.pytorch.Linear(...)

# Calibration step to initialize FP8 history
with transformer_engine.pytorch.fp8_autocast(enabled=False, calibrating=True):
    y = layer(x)
y.sum().backward()

# FP8 training step
with transformer_engine.pytorch.fp8_autocast():
    y = layer(x)
y.sum().backward()
```

**Comment by duomicoding** [comment]
@timmoon10 
got it, thank you very much!
