### ISSUE TITLE
Use a more standard syntax to specify the FW: pip install ...[jax]

### ISSUE THREAD

**Issue by nouiz** [NVIDIA/TransformerEngine#156]
Ideally, we should be able to use:
```
pip install ...[jax]
```

Instead of:
```
NVTE_FRAMEWORK=jax pip install ...
```

This would be easier to remember for end users.

**Comment by nouiz** [comment]
On a related note, what I think we should also do is change the default. Currently it build for all FW. I think the default should to be build for all FW installed and error out if no FW is installed.
@timmoon10 @ptrendx what do you think of that?

With that, we won't need to hack setuptool and hijack the extra_require mechanism for the ext_modules. It isn't done for that.

**Comment by timmoon10** [comment]
This would be a really nice API, but I don't see a nice way to make it work. As far as I can tell, these kinds of options ("extras") just add more dependencies and are not accessible during the build phase (especially `build_ext`). We could make some very intrusive modifications to the Setuptools build infrastructure, but that sounds risky. I could be wrong though and would be interested if you are aware of any other projects that expose complicated options this way.

https://github.com/NVIDIA/TransformerEngine/pull/235 doesn't quite match your proposal, but it does remove the need for `NVTE_FRAMEWORK` since it automatically detects the installed frameworks if `NVTE_FRAMEWORK` is not set.
