### ISSUE TITLE
setup.py installation error

### ISSUE THREAD

**Issue by antman1p** [NVIDIA/TransformerEngine#193]
I am getting a cuda_to _hip_mappings.py error when I run the setup.py installation

NVIDIA GEFORCE RTX 4090
5.15.90.1-microsoft-standard-WSL2 Ubuntu on WIndows 11
venv
CUDA 12.1
Python 3.10.6

```
Traceback (most recent call last):
  File "/home/antman/DEV/llmenv/TransformerEngine/setup.py", line 212, in <module>
    from torch.utils.cpp_extension import CUDAExtension
  File "/home/antman/DEV/llmenv/lib/python3.10/site-packages/torch/utils/cpp_extension.py", line 19, in <module>
    from .hipify import hipify_python
  File "/home/antman/DEV/llmenv/lib/python3.10/site-packages/torch/utils/hipify/hipify_python.py", line 34, in <module>
    from .cuda_to_hip_mappings import CUDA_TO_HIP_MAPPINGS
  File "/home/antman/DEV/llmenv/lib/python3.10/site-packages/torch/utils/hipify/cuda_to_hip_mappings.py", line 34, in <module>
    rocm_path = subprocess.check_output(["hipconfig", "--rocmpath"]).decode("utf-8")
  File "/usr/lib/python3.10/subprocess.py", line 420, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/lib/python3.10/subprocess.py", line 501, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/usr/lib/python3.10/subprocess.py", line 969, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.10/subprocess.py", line 1845, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
NotADirectoryError: [Errno 20] Not a directory: 'hipconfig'
```

**Comment by timmoon10** [comment]
Strange error. The exception comes from here:
https://github.com/pytorch/pytorch/blob/543b7ebb5045de7b6fd4dbff35e34c61946960fe/torch/utils/hipify/cuda_to_hip_mappings.py#LL34C1-L34C1
But it's clearly within a try-except block that should catch the `NotADirectoryError`.

**Comment by timmoon10** [comment]
To rule out whether this is a PyTorch or Transformer Engine bug, can you run `python -c "import torch.utils.cpp_extension"`?

**Comment by antman1p** [comment]
Well, that seems to have worked, but now i get a new error:
```
RuntimeError:
      The detected CUDA version (12.1) mismatches the version that was used to compile
      PyTorch (11.7). Please make sure to use the same CUDA versions.
```

**Comment by timmoon10** [comment]
It looks like you've hit a PyTorch bug that was just fixed last week (https://github.com/pytorch/pytorch/pull/99980).

Your error message makes me anticipate another problem. You've upgraded your CUDA driver to CUDA 12, but PyTorch still hasn't officially released a compatible version. Building PyTorch from source should work ([see here](https://discuss.pytorch.org/t/pytorch-for-cuda-12/169447)). But if you ask me, I'd suggest using the Docker container from https://catalog.ngc.nvidia.com/orgs/nvidia/containers/pytorch, at least until PyTorch makes an official release. The container should be configured to avoid the hipconfig error, which may be moot since it also comes with Transformer Engine installed.
