### ISSUE TITLE
Why is the first dimension `sequence_length` as opposed to `batch_size` in the input tensor

### ISSUE THREAD

**Issue by vgoklani** [NVIDIA/TransformerEngine#195]
Why does the library use `sequence_length` as the first dimension of the input-tensor as opposed to the `batch_size`? 

Is this just a choice of convention from RNNs or is the difference performance related? 

From the example code:

```python
bmm1 = torch.bmm(query.transpose(0, 1), key.transpose(0, 1).transpose(1, 2)) / self.norm_factor
```

    https://github.com/NVIDIA/TransformerEngine/blob/main/docs/examples/quickstart_utils.py#L93

I see two successive transpose(0, 1) operations?

Thanks!

**Comment by ksivaman** [comment]
Having either batch size or sequence length as the first dimension of the input tensor can be beneficial for performance depending on the attention implementation and some other details. Our choice to stick with sequence length as the first dimension was so that we can add support for [sequence parallelism](https://arxiv.org/abs/2205.05198). That being said, we will soon add a `batch_first` argument in our APIs that would optionally support input tensors with `batch_size` as their first dimension.

**Comment by vgoklani** [comment]
that makes sense, thank you!

**Comment by bryangopal** [comment]
> Having either batch size or sequence length as the first dimension of the input tensor can be beneficial for performance depending on the attention implementation and some other details. Our choice to stick with sequence length as the first dimension was so that we can add support for [sequence parallelism](https://arxiv.org/abs/2205.05198). That being said, we will soon add a `batch_first` argument in our APIs that would optionally support input tensors with `batch_size` as their first dimension.

any updates on the `batch_first` addition?

**Comment by timmoon10** [comment]
The attention module has logic to handle multiple formats (e.g. SBHD, BSHD). See:
https://github.com/NVIDIA/TransformerEngine/blob/666539f36275fa9c0fbc99f9ea50f2d6e29e336f/transformer_engine/pytorch/attention.py#L1821
However, we haven't exposed this in the Transformer layer yet. Pinging @cyanguwa.

**Comment by bryangopal** [comment]
@cyanguwa would appreciate an update!
