### ISSUE TITLE
Best practices for weight dtype and autocasting

### ISSUE THREAD

**Issue by c0g** [NVIDIA/TransformerEngine#438]
I might be confused here, but I'm curious of the following:

It seems like if we use TE's autocast with model dtype float32, we don't get to use FlashAttention since it requires the dtype to be bfloat16. If we set the model dtype to bfloat16 TE casting to FP8 will work, and we get FlashAttention, but then according to Gopher we might have convergence issues. 

Is this a real concern, and is there a recipe to fix this? Can TE's autocast also support casting to BFloat16 when possible?

**Comment by c0g** [comment]
MosaicML's [blog post](https://www.mosaicml.com/blog/coreweave-nvidia-h100-part-1) says to do both!

```python
with torch.autocast(device_type="cuda", dtype=torch.bfloat16):
    with te.fp8_autocast(enabled=True, fp8_recipe=fp8_recipe):
    # Run training step
```

**Comment by c0g** [comment]
Hmm actually found this comment: https://github.com/NVIDIA/TransformerEngine/issues/401#issuecomment-1703496730, which cast doubt on this conclusion. 

Does TE work with autocast?

**Comment by timmoon10** [comment]
Sorry for the confusion, I'm confused myself. If I remember correctly, I made that comment since I ran into issues when combining `te.fp8_autocast` and `torch.autocast`, but I haven't been able to reproduce those issues. I suppose combining multiple autocast types might lead to multiple casts (fp32 -> bf16 -> fp8), but Flash Attention/cuDNN attention is likely worth that overhead.

**Comment by ptrendx** [comment]
Hi @c0g, does @timmoon10 's comment clear the confusion? TE works with autocast - please open an issue if you see any problem with it :-).
