### ISSUE TITLE
Failed building wheel for transformer-engine

### ISSUE THREAD

**Issue by RuslanSel** [NVIDIA/TransformerEngine#459]
Ubuntu 18.04
python 3.11.5
conda
pip install --upgrade git+https://github.com/NVIDIA/TransformerEngine.git@stable
...
...
      [ 79%] Building CXX object common/CMakeFiles/transformer_engine.dir/util/cuda_driver.cpp.o
      /tmp/pip-req-build-j223vg5e/transformer_engine/common/util/cuda_driver.cpp:8:10: fatal error: filesystem: No such file or directory
       #include <filesystem>
                ^~~~~~~~~~~~

Thanks in advance.

**Comment by Zhihan1996** [comment]
Hello, did you figure out the issue? I am facing the same issue with cmake 3.28/3.29/3.30 and gcc 12.4.

**Comment by timmoon10** [comment]
This error message suggests that your compiler does not have C++17 support. You should first try building with verbose output so that we can see what compiler command is being run:
```
cd transformer_engine
pip install -v -v -v .
```
This will spit out a lot of info, so you'll need to search for where `cuda_driver.cpp` is being compiled. Some possible outcomes:
- CMake is not compiling with GCC 12.4, but is using an older compiler. Set `CXX` in the environment to tell CMake what C++ compiler you want to use.
- CMake is using the right compiler, but is not enabling C++17 support (look for `-std=c++17` or `-std=gnu++17` flags). This would be very strange since we explicity tell CMake to use C++17: https://github.com/NVIDIA/TransformerEngine/blob/a132ac499d3b388b6fe658dfda03829a06edc3c3/transformer_engine/common/CMakeLists.txt#L11
- CMake is using the right compiler and has enabled C++17.

See https://github.com/NVIDIA/TransformerEngine/issues/355#issuecomment-2394353816 for more guidance on build errors.
