### ISSUE TITLE
_ZN18transformer_engine6getenvIiEET_RKSsRKS1_ on the latest main branch

### ISSUE THREAD

**Issue by leiwen83** [NVIDIA/TransformerEngine#756]
Hi,

When I try the example located in docs/examples/te_llama with latest code, met below error:

/usr/local/lib/python3.10/dist-packages/transformer_engine_extensions.cpython-310-x86_64-linux-gnu.so: undefined symbol: _ZN18transformer_engine6getenvIiEET_RKSsRKS1_

**Comment by lucifer1004** [comment]
Same here.

**Comment by danthe3rd** [comment]
Getting the same as well on `release_v1.5`. `release_v1.4` works fine tho

**Comment by ptrendx** [comment]
@pggPL Could you take a look at this issue?

**Comment by jinzex** [comment]
The issue happens because we recently included `common/util/system.h` into PyTorch source CPP files at https://github.com/NVIDIA/TransformerEngine/pull/713/files to utilize the `transformer_engine::getenv` method. As a result, the PyTorch `transformer_engine_extensions` will now search for symbols within the `libtransformer_engine.so` library.

However, if the user builds TransformerEngine in a local environment (conda or PyPI), because the pre-built PyTorch, either from conda or PyPI, has the CXX11_ABI set as False, whereas the common library is using the new CXX11_ABI. As a result, there will be an undefined symbol problem when importing `transformer_engine_extensions`.

The following could be a possible fix: compile system.cpp directly to avoid linking directly with libtransformer_engine.so. Please let me know if this makes sense, and I could open a PR for it.

https://github.com/NVIDIA/TransformerEngine/blob/bfe21c3d68b0a9951e5716fb520045db53419c5e/setup.py#L443-L449

possible fix:
```python
    sources = [
        src_dir / "common.cu",
        src_dir / "ts_fp8_op.cpp",
        # We need to compile system.cpp because the extension uses transformer_engine::getenv.
        # This is a workaround to avoid linking directly with libtransformer_engine.so.
        root_path / "transformer_engine" / "common" / "util" / "system.cpp",
    ] + \
    _all_files_in_dir(extensions_dir)
```

**Comment by timmoon10** [comment]
Ah, ABI issues make things challenging. If ABI incompatibility breaks `transformer_engine::getenv`, there's no reason to believe we can rely on any other C++ interfaces between `libtransformer_engine.so` and the PyTorch extension. This makes me think the right solution is to make the following refactors:
- Only use C or header-only C++ functions from the common library in the PyTorch extensions.
- If a C++ function in the common library can't be made header-only, its source code should be duplicated within the PyTorch extensions.

Ugly.

Similar logic would also apply to the Paddle extension, which has a similar build system as PyTorch.

**Comment by yueyericardo** [comment]
@timmoon10 Thanks for the comments and proposed solution, I agree with it.
Another possible solution, for example, could we choose to build `libtransformer_engine.so` with the same CXX11_ABI as pytorch (`torch._C._GLIBCXX_USE_CXX11_ABI`) to ensure ABI compatibility?
