### ISSUE TITLE
[Question] ub_tp_comm_overlap config setup

### ISSUE THREAD

**Issue by tylaar** [NVIDIA/TransformerEngine#827]
Hi there, 
I found there is very little doc regarding about ub_tp_comm_overlap config during model setup both in TransformerLayer and AttentionLayer, it seems opening up ub_tp_comm_overlap=True will result in "ub_manager not initialized" issue, but there is not too much content about the practise regarding how to call initialize_ub function in the repo. Is there a link or way to tell how to setup this ub_manager for tp comm overlap? 

Thanks a lot

**Comment by ptrendx** [comment]
Adding @denera for visibility.

I agree that currently there is pretty much zero documentation around UB usage. We are working on making that feature easier to use and document it better.

**Comment by tylaar** [comment]
> Adding @denera for visibility.
> 
> I agree that currently there is pretty much zero documentation around UB usage. We are working on making that feature easier to use and document it better.

Thanks @ptrendx! Any quick guide/introduction or sample code I could use to do some quick play around?

**Comment by tylaar** [comment]
Okay so during the last few hours I played around a little by setting ub_tp_comm_overlap=True, and things I've overcame listed as below:
1. GDRCopy seems to be mandatory now (not sure why my previous code piece for UB is using macro to comment them out), so I installed GDRCopy according to their instruction
2. Then I found my setup.py has a logic which is judging if using "userbuffer_use_c10d_pg" then not to append -DMPI and -DGDR , thus loading up tex at this building version failed since in UB using mpi interface looks to be a must have and will throw something like "undefined symbol ompi_mpi_char" stuff. This is solved by not using c10d_pg, instead directly using MPI + GDR
3. This is the step that puzzles me now. After performing two steps, once I start to initialize_ub it will throw sth like: 
`*** The MPI_Comm_rank() function was called before MPI_INIT was invoked.
*** This is disallowed by the MPI standard.
*** Your MPI job will now abort.` now I have no Idea where the mpi_init is called during booting up TE then

**Comment by denera** [comment]
Hi @tylaar -- the NVLink collectives provided by userbuffers code in `transformer_engine/pytorch/csrc/userbuffers` is bootstrapped with MPI on initialization. PR #760 removes this dependency, but it has not been upstreamed yet. In your case, I'm guessing that the easiest way to initialize MPI before initializing userbuffers is to call `torch.distributed.init_proces_group(backend="mpi")` at the top of your code.

**Comment by tylaar** [comment]
Hi @denera, thanks for the quick response. I think my situation won't be that easily mitigated by setting the backend to mpi. Previous code stack is mainly using nccl as backend, and when I switch to mpi it shows that current torch is not compiled with MPI and thus need to be rebuilt ... 

Also, not sure if changing this could affect other communication performance previously on nccl. Is that safe? 
Any other workaround for this situation ? 

Many thanks!

**Comment by tylaar** [comment]
Hi @denera , thanks for the quick reply! 

What if I am using torchrun after with arguments like:
`--node_rank=0 --nproc_per_node=<N> --nnodes=1 --rdzv_endpoint=10.xx.xx.xx:xxxx ` 
after the mpiexec ? It appears to report error inside torchrun saying "The server socket has failed to bind to [::]:xxxx (errno: 98 - Address already in use)"

**Comment by denera** [comment]
Hi @tylaar -- There is no way to use `mpiexec` and `torchrun` at the same time, and it's also not necessary anyway because `torch.distributed` supports launching with `mpiexec`.

For example, if your `torchrun` launch is like
```bash
$ torchrun --node_rank=0 --nproc_per_node=<N> --nnodes=1 --rdzv_endpoint=<1.2.3.4>:<1234> python <file.py> <args>
```
the equivalent `mpiexec` launch would be
```bash
$ mpiexec -np <N> -x MASTER_ADDR=<1.2.3.4> -x MASTER_PORT=<1234> -x PATH python <file.py> <args>`
```
The default behavior for both of these is to launch on a single node so `--node_rank=0` and `--nnodes=1` are not necessary.

This is the same `mpiexec` command I shared with you in my previous comment, and I've verified that it works on our compute cluster with rdzv_endpoint address set as MASTER_ADDR and rdzv_endpoint port set as MASTER_PORT.

I was also able to successfully launch multi-node `torch.distributed` jobs with `mpiexec` instead of `torchrun` too, simply by replacing `-np <N>` with `-hostfile myhosts.txt` where `myhosts.txt` contains a list of network addresses for each node and the # of processes I want to launch on each one.

The only core requirement for `torch.distributed` is to specify `-x MASTER_ADDR=<1.2.3.4> -x MASTER_PORT=<1234>` as the address and port for your primary node (usually root node 0) that has passwordless access to every other node. `torch.distributed.init_process_group(...)` depends on these environment variables to correctly rendezvous across all the processes that call into the initialization, regardless of how those processes have originally been launched.

**Comment by tylaar** [comment]
hey @denera , sorry for the late reply. So i've tried several way to bypass the mpi stuff these days and haven't figured out a good way due to my underlying infra level incompatibility issue (yeah, like pytorch stuff I've encountered before ...). I guess probably I will just wait for your PR get merged and stick to latest version of TE then. I will close this first then. Thanks again for your effort!
